FROM golang:1.26-alpine AS compilacion
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o worker .

FROM alpine:latest
WORKDIR /app

COPY --from=compilacion /app/worker .
COPY vista ./vista
COPY static ./static

EXPOSE 8080
CMD ["./worker"]
