FROM golang:1.26-alpine AS compilacion
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o middleware ./middleware

FROM alpine:latest
WORKDIR /app

COPY --from=compilacion /app/middleware .

EXPOSE 8080
CMD ["./middleware"]
